# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - superkudosmsgraph

on:
  push:
    branches:
      - master
    paths:
      - 'MyKudos.MSGraph.Api/**/*'
    workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

       # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore "MyKudos.Gateway\MyKudos.Gateway.csproj"
          dotnet build --configuration Release "MyKudos.Gateway\MyKudos.Gateway.csproj"
          dotnet publish -c Release "MyKudos.Gateway\MyKudos.Gateway.csproj" -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'superkudosgateway'
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_27F6926C20F74390A5DB341CE93277B4 }}
