# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - superkudoschat

on:
  push:
    branches:
      - master
    paths:
      - 'SuperKudos.Copilot/**/*'
  workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          include-prerelease: false

       # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore "SuperKudos.Copilot\SuperKudos.Copilot.csproj"
          dotnet build --configuration Release "SuperKudos.Copilot\SuperKudos.Copilot.csproj"
          dotnet publish -c Release "SuperKudos.Copilot\SuperKudos.Copilot.csproj" -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E82ADAAA6C8E479E8F2E951582DF5FBA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EA31575E689D49138A4E653A0A4A7B21 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8C8D010FCFBA44B2A35E75E3868152B8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'superkudoschat'
          slot-name: 'Production'
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
          
